### ISSUE TITLE
Update .NET Core to 3.1

### ISSUE THREAD

**Issue by rjperes** [svenheden/csharp-models-to-typescript#48]
When running the project we get a warning about an unsupported .NET Core version (2.0).
This MR by @yavari addresses this:
https://github.com/svenheden/csharp-models-to-typescript/pull/46

**Comment by svenheden** [comment]
This is now resolved in v0.19.0

**Comment by alessior81** [comment]
the problem still remains: there is a warning and in any case the file is not generated: 
warning message: (NET 5.0)
C:\Program Files\dotnet\sdk\**5.0.100**\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138

**Comment by svenheden** [comment]
Thanks @alessior81, this is now resolved in v0.19.1.

**Comment by rjperes** [comment]
This problem is indeed closed, but, for some reason, the casing of the new files is different than before. Meaning, now ID is cased as Id.

**Comment by svenheden** [comment]
> This problem is indeed resolved, but, for some reason, the casing of the new files is different than before. Meaning, now ID is cased as Id.

Yeah that's a side effect of [this](https://github.com/svenheden/csharp-models-to-typescript/pull/41#issuecomment-691692329)
